name       : libwps
version    : 0.4.8
release    : 4
source     :
    - http://internode.dl.sourceforge.net/project/libwps/libwps/libwps-0.4.8/libwps-0.4.8.tar.xz : e478e825ef33f6a434a19ff902c5469c9da7acc866ea0d8ab610a8b2aa94177e
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : Microsoft Works file format import filter
description: |
    Libwps is a Microsoft Works file format import filter based on top of the librevenge.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

