name       : libwps
version    : 0.4.4
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/libwps/libwps/libwps-0.4.4/libwps-0.4.4.tar.xz : b7c564bba7bc9058c524eaf94cb43448832aa03e3d763b98e11ee12d25082df4
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : Microsoft Works file format import filter
description: |
    Libwps is a Microsoft Works file format import filter based on top of the librevenge.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
