name       : libwps
version    : 0.4.6
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/libwps/libwps/libwps-0.4.6/libwps-0.4.6.tar.xz : e48a7c2fd20048a0a8eaf69bad972575f8b9f06e7497c787463f127d332fccd0
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : Microsoft Works file format import filter
description: |
    Libwps is a Microsoft Works file format import filter based on top of the librevenge.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
