name       : libwps
version    : 0.4.10
release    : 5
source     :
    - https://netcologne.dl.sourceforge.net/project/libwps/libwps/libwps-0.4.10/libwps-0.4.10.tar.xz : 1421e034286a9f96d3168a1c54ea570ee7aa008ca07b89de005ad5ce49fb29ca
license    :
    - LGPL-2.1-or-later
    - MPL-2.0
component  : programming.library
summary    : Microsoft Works file format import filter
description: |
    Libwps is a Microsoft Works file format import filter based on top of the librevenge.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

