name       : libwps
version    : 0.4.5
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/libwps/libwps/libwps-0.4.5/libwps-0.4.5.tar.xz : 8e175ab9339d447a285a1533bfdc405432b9a275e4f3a98690ffaf12fe7f4d4a
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : Microsoft Works file format import filter
description: |
    Libwps is a Microsoft Works file format import filter based on top of the librevenge.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
